import img1A from "../img/img1.jpg";
import img1B from "../img/img1.jpg";
import img1C from "../img/img1.jpg"; 
import img1D from "../img/img1.jpg"; 
import img1E from "../img/img1.jpg"; 
import img1F from "../img/img1.jpg"; 
import img2 from "../img/img1.jpg";
import img3 from "../img/img1.jpg";
import img4 from "../img/img1.jpg";
const data = [
    {
        userId: "daofidjsifjioadfoidasiofajso",
        postStatus: "sold",
        promotion: "free shipping",
        vehicleModal: "gla suv",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "suv",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1A,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1B,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1C,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1D,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1E,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1F,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1B,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1A,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1D,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1F,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },
    {
        userId: "daofidjsifjioa4545545ofajso",
        postStatus: "available",
        promotion: "$400 shipping",
        vehicleModal: "gle coupe",
        vehicleMake: "mercedes",
        vehicleYear: 2021,
        vehiclePrice: 36230,
        vehicleMileage: 10000,
        milesPerGallon: "25/32 mpg",
        bodyStyle: "coupe",
        engineType: "2.4l",
        interiorColor: "black",
        drivetrain: "2wd",
        numberOfKeys: 2,
        exteriorColor: "white",
        transmission: "automatic",
        doors: 2,
        vin: "45645612123",
        seller: {
            id: "0000",
            firstName: "musa",
            lastName: "gradi",
        },
        images: {
            image1: img1E,
            image2: img2,
            image3: img3,
            image4: img4,
        },
        updatedAt: Date.now(),
        createdAt: Date.now()
    },

];

export { data };